[package]
name = "app"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]
edition = "2018"

[dependencies]
juniper = "0.12"
actix-web = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
env_logger = "0.6"
futures = "0.1"
entities = { path = "../entities" }
